### ISSUE TITLE
Users are not showing in contact list.

### ISSUE THREAD

**Issue by MahipalV12** [AppLozic/Applozic-Android-Chat-Sample#5]
i have 23 users on dashboard but they are not showing in contact list , only 2 are showing
![screenshot_20170918-171035](https://user-images.githubusercontent.com/28589483/30540393-99af4b38-9c94-11e7-823b-21923beddb60.jpg)
o.
 version : 1.4

**Comment by Sunilkumarr** [comment]
@MahipalV12  Add the applozic-settings.json file  from this link 

[https://www.applozic.com/docs/android-chat-sdk.html#customization](https://www.applozic.com/docs/android-chat-sdk.html#customization
)
and  in **applozic-settings.json** file  find the  **"registeredUserContactListCall"** make it to true -- > 
  **"registeredUserContactListCall": true**

**Comment by MahipalV12** [comment]
Thanks @Sunilkumarr , its resolved.
