### ISSUE TITLE
Push Notification are not working on new messages

### ISSUE THREAD

**Issue by MahipalV12** [AppLozic/Applozic-Android-Chat-Sample#6]
FCM key already added and tested. 

Sno | Device Key | Registration Id | Status | Created Time | Device Type
-- | -- | -- | -- | -- | --
1 | cxxxe-c6x6-4xx9-92ab-fxxxe0 |   | Not Valid | 2017-09-18 11:27:49.626 | ANDROID

**Comment by Sunilkumarr** [comment]
@MahipalV12 Can you check the push notification setup is done from this ? currently fcm registration  token not updating to applozic server

[https://www.applozic.com/docs/android-chat-sdk.html#step-4-push-notification-setup](https://www.applozic.com/docs/android-chat-sdk.html#step-4-push-notification-setup)

**Comment by MahipalV12** [comment]
Thanks.
