### ISSUE TITLE
No Push Notification when app is quite

### ISSUE THREAD

**Issue by bharatguptacgt** [AppLozic/Applozic-Android-Chat-Sample#7]
Android app is not getting notification when app is quite i.e. even not in background. How to resolve this?
i am using this line 
ApplozicClient.getInstance(SplashScreenActivity.this).enableNotification();
or i should say not getting FCM when i am offline

**Comment by Sunilkumarr** [comment]
Can you put your applicationKey and userId in this push notification tool link https://www.applozic.com/docs/push-notification-test.html    and what response your getting in tool page for     Registration id and status  in this fields

**Comment by bharatguptacgt** [comment]
resolved
