### ISSUE TITLE
Application crashes when we try to enter a message in chat

### ISSUE THREAD

**Issue by RichieGladwin** [AppLozic/Applozic-Android-Chat-Sample#9]
java.lang.IllegalArgumentException: The topic name MUST NOT contain any wildcard characters (#+)

If an email consist of + or # characters then the chat crashes...

Ex: venkat+02@mobellotech.com

**Comment by Sunilkumarr** [comment]
What is the sdk version your using can you updated to latest sdk ?  In userId the special characters are not allowed like +* /#

**Comment by RichieGladwin** [comment]
But it works on ios..

**Comment by Sunilkumarr** [comment]
we dont recommend to   special characters  in userId as it causes issues  in MQTT  . I have added the check for that in latest versions . Attach your ApplozicMqttService.java file here
